# Generated by Django 4.2.8 on 2023-12-16 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsobject',
            name='guid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
